name: Python Github Actions
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Option input
        required: true
        default: input_1
        options:
          - input_1
          - input_2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
         python-version: '3.10'
      - name: if1
        if: ${{github.events.inputs.environment == 'input_1'}}
        env:
          TEST_ENV: INPUT_1 WAS CHOSEN
        run: |
           echo "INPUT: $TEST_ENV"
      - name: if2
        if: ${{github.events.inputs.environment == 'input_2'}}
        env:
          TEST_ENV: INPUT_2 WAS CHOSEN
        run: |
           echo "INPUT: $TEST_ENV"
      - name: else
        if: ${{! github.events.inputs.environment}}
        env:
          TEST_ENV: NONE OF THEM SO PROBABLY PUSH ACTION :DD
        run: |
          echo "INPUT: $TEST_ENV"
      - name: Run script
        run: |
          python sample.py
      #- uses: stefanzweifel/git-auto-commit-action@v4
      #  with:
      #    commit_message: The hour has changed
  context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"
