name: Python Github Actions
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Option input
        required: true
        default: input_1
        options:
          - input_1
          - input_2

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up Python 3.10
       uses: actions/setup-python@v4
       with:
        python-version: '3.10'
     - name: Run script
       run: |
         python sample.py