name: Python Github Actions
on:
  push:
    branches: ['main']
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Option input
        required: true
        default: input_1
        options:
          - input_1
          - input_2

jobs:
 build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
     - name: Set up Python 3.10
       uses: actions/setup-python@v4
       with:
        python-version: '3.10'
     - name: Print input
       run: |
          echo "INPUT: ${{github.event.inputs.environment}}"
     - name: Print context
       run: |
          echo '${{ toJSON(github) }}'
     - name: Run script
       run: |
         python sample.py
     #- uses: stefanzweifel/git-auto-commit-action@v4
     #  with:
     #    commit_message: The hour has changed
